export default {
    status: [
        { id: 1, text: "Confirmed" },
        { id: 2, text: "Declined" },
        { id: 3, text: "Evaluation Complete" },
        { id: 4, text: "Unrecoverable" },
        { id: 5, text: "Quote Sent" },
        { id: 6, text: "Complete" },
        { id: 7, text: "Evaluating" },
        { id: 8, text: "En Route" },
        { id: 9, text: "Closed" },
    ],
    progress: [
        { id: 1, text: "Waiting for parts" },
        { id: 2, text: "Waiting for online" },
        { id: 3, text: "In Progress" },
        { id: 4, text: "Alex" },
        { id: 5, text: "Approved" },
        { id: 6, text: "Completed" },
        { id: 7, text: "Cloning" },
        { id: 8, text: "Paid" },
        { id: 9, text: "None" },
        { id: 10, text: "Waiting for Drive" },
        { id: 11, text: "Crackerz" },
        { id: 12, text: "Closed" },
        { id: 13, text: "Copying Files" },
        { id: 14, text: "Shipped" },
        { id: 15, text: "File List Sent" },
        { id: 16, text: "Invoice Sent" },
        { id: 17, text: "Client Away" },
    ],
    assigned: [
        { id: 1, text: "Ilya" },
        { id: 2, text: "Alex" },
        { id: 3, text: "None" },
    ],
    format: [
        { id: 1, text: "Windows" },
        { id: 2, text: "macOS" },
        { id: 3, text: "Linux" },
    ],
    yes_or_no: [
        { id: 0, value: false, text: "NO" },
        { id: 1, value: true, text: "YES" },
    ], 
    paid_or_no: [
        { id: 0, value: false, text: "NO" },
        { id: 1, value: true, text: "YES" },
    ],
};
